### ISSUE TITLE
App does not open Sonoma 

### ISSUE THREAD

**Issue by thegoldknight** [breitnw/micromusic#5]
Hey, I downloaded the new release but now the app doesn't even launch. When I open it, I see a little blip showing the app opening on the dock for half a second, and then it disappears.

_Originally posted by @thegoldknight in https://github.com/breitnw/micromusic/issues/2#issuecomment-2192765529_

**Comment by breitnw** [comment]
Weird... could you run the app with the terminal and let me know what the output is? I have a hunch that it's a bug with one of the applescript files I changed in the update (and if so, I think I know what the issue is) but I want to verify. You should be able to just run this command in the terminal:

```bash
/Applications/micromusic.app/Contents/MacOS/micromusic
```

**Comment by thegoldknight** [comment]
```
2024-06-27 09:48:29.551 micromusic[4605:78274] dyld[4606]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <59BCBF20-A7C4-346B-8B44-3D8C60C1CE41> /Applications/micromusic.app/Contents/Resources/bin/micromusic
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)

```

**Comment by breitnw** [comment]
Ok, well that's not what I expected. Thought I resolved that problem a couple releases back, but I guess it's still here. If you want a temporary fix you may be able to run `brew install xz`, but I'll look for a permanent one.

**Comment by thegoldknight** [comment]
Would I have to compile from source to have this work? Because I have not done that. 

> If you want a temporary fix you may be able to run `brew install xz`, but I'll look for a permanent one.

btw this doesn't work

**Comment by breitnw** [comment]
You shouldn't need to, since it's a dylib causing the issue... Could you run with the terminal again and see if the output changed?

**Comment by thegoldknight** [comment]
`Applications/micromusic.app/Contents/MacOS/micromusic
2024-06-27 10:01:28.523 micromusic[6386:92134] dyld[6387]: Library not loaded: /opt/homebrew/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib
  Referenced from: <59BCBF20-A7C4-346B-8B44-3D8C60C1CE41> /Applications/micromusic.app/Contents/Resources/bin/micromusic
  Reason: tried: '/opt/homebrew/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib' (no such file), '/opt/homebrew/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib' (no such file)`

**Comment by breitnw** [comment]
looks like it's searching for the sdl2 library now, which you can also install with brew. But at this rate, you'll have to install all the libraries yourself to get it working, which obviously isn't a solution. Looking into the issue right now.

**Comment by breitnw** [comment]
Try this: [test.zip](https://github.com/user-attachments/files/16006102/test.zip) (I know this looks suspicious i probably shouldve named it something other than test.zip i'm sorry lol)

I used [dylibbundler](https://github.com/auriamg/macdylibbundler/) to package the dylib files with the binary, so I'm hoping this will work.

**Comment by thegoldknight** [comment]
> Try this: [test.zip](https://github.com/user-attachments/files/16006102/test.zip) (I know this looks suspicious i probably shouldve named it something other than test.zip i'm sorry lol)
> 
> I used [dylibbundler](https://github.com/auriamg/macdylibbundler/) to package the dylib files with the binary, so I'm hoping this will work.

Everything works!

**Comment by breitnw** [comment]
Perfect! Thanks so much for your help. I'll make a new release with the fixed binary.
